services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev_db
    ports:
      - "3308:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge