services:
  app:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: huy_app
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge